### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by boneskull** [uecasm/rs4cc#2]
just wanted to say thanks for this--I needed it but am not well-versed enough in CC to do it myself. 

if you're interested in some examples of use, I can send some once I have something working. I'm working on using a JSON config to keep a list of items in stock. 

I hope to apply hysteresis to avoid RS constantly crafting a single item over and over (e.g., you want to keep 64 bottles in stock, but if a machine is continually using bottles, RS keeps autocrafting a single bottle to keep the count at 64).

**Comment by uecasm** [comment]
Did you look at the Storage Manager example in the wiki?

In the next version of the mod (coming soon), I'll be bringing out a better version that's included by default.

**Comment by boneskull** [comment]
Oh awesome, totally missed that. GitHub app for iOS doesn't seem to have an obvious wiki link anywhere. 

looks like there are quite a few possibilities here, though maybe limited by RS' api (or lack thereof).  anyway, mainly just wanted to send words of encouragement!

**Comment by boneskull** [comment]
re this:

> If you completely run out of a red item (none in storage and no known crafting pattern) then the internal name will appear instead of the "normal" name. This is because it looks the name up via RS, and if there's nothing there it can't translate it.

would it be reasonable to access some other system to determine the missing info?  if I wanted to attempt this, can you point me in the right direction (again, new to CC)?

**Comment by uecasm** [comment]
Don't worry, the next version of the mod will fix this.

**Comment by uecasm** [comment]
FYI, the next version has now been [released](https://www.curseforge.com/minecraft/mc-mods/refined-storage-for-computercraft/), and it includes the new [AutoStock](https://github.com/uecasm/rs4cc/wiki/AutoStock) program.

**Comment by boneskull** [comment]
@uecasm awesome, thank you! works great
