### ISSUE TITLE
Support 1.16.3

### ISSUE THREAD

**Issue by Emyrk** [uecasm/rs4cc#3]
Hey I would love to add this mod, but I'm on 1.16.3. If this is compatible with that, can you upload to support that patch as well?

**Comment by uecasm** [comment]
No, one of the features in 1.1.0 relies on something that was added in RS 1.9.10, which also requires MC 1.16.4.  You'll need to upgrade.  Fortunately, most mods and modpacks have already upgraded to 1.16.4 (and some might just work as is if you're lucky).

**Comment by Emyrk** [comment]
Damn, thanks for the response
