### ISSUE TITLE
The method getItems() does not work on servers

### ISSUE THREAD

**Issue by squarism** [uecasm/rs4cc#7]
The API call `refinedstorage.getItems()` errors with `invalid dist dedicated server` when used on a server.  Moving the entire world to a single player game worked fine (same blocks, same lua).

**Comment by uecasm** [comment]
My apologies, I missed this notification somehow.  But I can't reproduce it in a test world with the current version, so either it's been fixed along the way or you'll need to provide more details on how to break it.
